from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 546)
        MainWindow.setStyleSheet("QMainWindow{background-color: rgb(58, 58, 58);background-image: url(src/Besplatan-DEMO.png);}"
"QPushButton{border: 2px solid rgb(0, 154, 231);border-radius: 10px;background-color: rgb(204, 204, 204);}"
"QGroupBox{border: 1px solid rgb(0, 154, 231);color: #FFF;}"
"QLabel{color: rgb(255, 255, 255);}"
"QMenuBar::item:selected{background: transparent;border: 1px solid  rgb(0, 154, 231);}"
"QMenuBar::item{background: transparent;}"
"QMenuBar{color:#fff;}span{color:red;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 450, 101, 31))
        font = QtGui.QFont("MS Reference Sans Serif",10,QtGui.QFont.Bold)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.parcourir = QtWidgets.QPushButton(self.centralwidget)
        self.parcourir.setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.parcourir.setGeometry(QtCore.QRect(690, 30, 91, 31))
        self.parcourir.setFont(font)
        self.parcourir.setObjectName("parcourir")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(200, 30, 471, 31))
        self.textEdit_3.setPlaceholderText("Selectionner votre fichier XMI")
        self.textEdit_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 171, 31))
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 761, 81))
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.NL = QtWidgets.QTextEdit(self.groupBox)
        self.NL.setGeometry(QtCore.QRect(0, 20, 761, 61))
        font.setPointSize(9)
        self.NL.setFont(font)
        self.NL.setPlaceholderText("Ex : le client doit étre majeur")
        self.NL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.NL.setObjectName("NL")
        self.clear = QtWidgets.QPushButton(self.groupBox)
        self.clear.setGeometry(QtCore.QRect(730, 30, 21, 23))
        self.clear.setFont(font)
        self.clear.setStyleSheet("QPushButton{border: 1px solid rgb(0, 154, 231);background-color:#FFF;border-radius:6px;}")
        self.clear.setObjectName("clear")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 240, 761, 171))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.OCL = QtWidgets.QTextEdit(self.groupBox_2)
        self.OCL.setGeometry(QtCore.QRect(0, 20, 761, 151))
        self.OCL.setPlaceholderText("Ex : Context   Client\n            inv :    age >= 18")

        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OCL.setFont(font)
        self.OCL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.OCL.setObjectName("OCL")
        self.context = QtWidgets.QPushButton(self.centralwidget)
        self.context.setGeometry(QtCore.QRect(560, 450, 101, 31))
        font.setFamily("MS Reference Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        self.context.setFont(font)
        self.context.setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.context.setObjectName("context")
        self.contraintes = QtWidgets.QPushButton(self.centralwidget)
        self.contraintes.setGeometry(QtCore.QRect(340, 450, 200, 31))
        self.contraintes.setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contraintes.setFont(font)
        self.contraintes.setObjectName("contraintes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFermer = QtWidgets.QAction(MainWindow)
        self.actionFermer.setCheckable(True)
        self.actionFermer.setObjectName("actionFermer")
        self.actionParam_tres = QtWidgets.QAction(MainWindow)
        self.actionParam_tres.setObjectName("actionParam_tres")
        self.menuFichier.setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionFermer)
        self.menuFichier.addAction(self.actionParam_tres)
        self.menubar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        self.clear.clicked.connect(self.NL.clear)
        self.actionFermer.triggered.connect(MainWindow.close)
        self.clear.clicked.connect(self.OCL.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Contrainte"))
        self.parcourir.setText(_translate("MainWindow", "Parcourir"))
        self.label_3.setText(_translate("MainWindow", "Diagramme de Classe"))
        self.groupBox.setTitle(_translate("MainWindow", "Langage Naturel"))
        self.clear.setText(_translate("MainWindow", "X"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Contrainte OCL"))
        self.context.setText(_translate("MainWindow", "Contextes"))
        self.contraintes.setText(_translate("MainWindow", "Toutes les Contraintes"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.actionFermer.setText(_translate("MainWindow", "Fermer"))
        self.actionFermer.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionParam_tres.setText(_translate("MainWindow", "Paramêtres"))

if __name__ == "__main__":
    from sys import exit, argv
    app = QtWidgets.QApplication(argv)
    MainWindow = QtWidgets.QMainWindow()
    Ui_MainWindow().setupUi(MainWindow)
    MainWindow.show()
    exit(app.exec_())

